#!/usr/bin/env python3

import glob
import os
import pathlib

PANO_DIR_LOCAL="../panos/"
PANO_DIR_OTHER="../../web-sandbox/panos/"
MENU_HTML_FILENAME="../menu.html"

source_filenames = []
source_files = glob.glob(PANO_DIR_LOCAL + "*.jpg", recursive=False)
source_filenames.extend([pathlib.Path(x).stem for x in source_files])
source_files = glob.glob(PANO_DIR_OTHER + "*.jpg", recursive=False)
source_filenames.extend([pathlib.Path(x).stem for x in source_files])

header = """
<!-- This file is generated by tools/gen_menu.py - edit at your own peril -->
<html>
<head>
<title>360 Panorama Menu</title>
<style>
body {
  background-color: #fff;
  font-family: Monospace;
}
.panoMenu {
  display: grid;
  grid-gap: 10px;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
}
.panoMenu img {
  width: 100%;
  border-radius: 10px;
}
.panoMenu .item {
  position: relative;
  overflow: hidden;
}
.panoMenu .item img {
  vertical-align: middle;
}
.panoMenu .caption {
  margin: 0;
  padding: 1em;
  position: absolute;
  z-index: 1;
  bottom: 0;
  left: 0;
  width: 100%;
  max-height: 100%;
  overflow: auto;
  box-sizing: border-box;
  transition: transform 0.5s;
  transform: translateY(100%);
  background: rgba(0, 0, 0, 0.4);
  color: rgb(255, 255, 255);
  border-bottom-left-radius: 10px;
  border-bottom-right-radius: 10px;
}
.panoMenu .item:hover .caption {
  transform: translateY(0%);
}
.panoMenu {
  font-size: 1rem;
}
.title {
  font-size: 2em;
}
</style>
</head>
<body>
<p class="title">360 Snapshots - Desktop, Mobile & VR</p>
<div class="panoMenu">
"""

footer = """</div>
</body>
</html>"""

print(f"Writing HTML to {MENU_HTML_FILENAME} ")
with open(MENU_HTML_FILENAME, 'w') as f:
    print(header, file=f)

    for source_file in source_filenames:
      
        source_file = source_file.replace('../', '')
        print("working on: ", source_file)
        
        caption = source_file.replace('.jpg', '')
        caption = caption.replace('_', ' ')
        caption = caption.replace('-', ' ')
        caption = caption[(caption.rfind('/') + 1):].upper()

        item = f"""
            <div class="item">
                <a href="index.html?eqr=panos/{source_file}.jpg" target="_blank">
                    <img src="./panos/{source_file}.jpg" />
                    <span class="caption">{caption}</span>
                </a>
            </div>"""
        print(item, file=f)

    print(footer, file=f)
