#!/usr/bin/env python3

import glob
import os
import pathlib
import argparse

os.chdir("..")

parser = argparse.ArgumentParser(allow_abbrev=False)

parser.add_argument(
    "--mode",
    required=True,
    dest="mode",
    choices={"local", "publish"},
    help="Specify mode to write files",
)

args = parser.parse_args()

PANO_DIR_LOCAL="panos/"
PANO_DIR_OTHER="../web-sandbox/panos/"

if args.mode=='local':
    MENU_HTML_FILENAME="menu.html"
else:
    MENU_HTML_FILENAME="tools/site/menu.html"

source_filenames = []
source_files = glob.glob(PANO_DIR_LOCAL + "*.jpg", recursive=False)

if args.mode=='local':
    source_filenames.extend(source_files)
else:
    source_filenames.extend([os.path.join("panos", pathlib.Path(x).name) for x in source_files])

source_files = glob.glob(PANO_DIR_OTHER + "*.jpg", recursive=False)
if args.mode=='local':
    source_filenames.extend(source_files)
else:
    source_filenames.extend([os.path.join("panos", pathlib.Path(x).name) for x in source_files])

source_filenames.sort()

header = """
<!-- This file is generated by tools/gen_menu.py - edit at your own peril -->
<html>
<head>
<title>360 Panorama Menu</title>
<style>
body {
  background-color: #99d;
  font-family: Monospace;
}
.panoMenu {
  display: grid;
  grid-gap: 10px;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
}
.panoMenu img {
  width: 100%;
  border-radius: 20px;
}
.panoMenu .item {
  position: relative;
  overflow: hidden;
}
.panoMenu .item img {
  vertical-align: middle;
}
.panoMenu .caption {
  margin: 0;
  padding: 1em;
  position: absolute;
  z-index: 1;
  bottom: 0;
  left: 0;
  width: 100%;
  max-height: 100%;
  overflow: auto;
  box-sizing: border-box;
  transition: transform 0.5s;
  transform: translateY(100%);
  background: rgba(0, 0, 0, 0.4);
  color: rgb(255, 255, 255);
  border-bottom-left-radius: 20px;
  border-bottom-right-radius: 20px;
}
.panoMenu .item:hover .caption {
  transform: translateY(0%);
}
.panoMenu {
  font-size: 1rem;
}
.title {
  font-size: 2em;
  color: #ff8;
  text-align: center;
}
</style>
</head>
<body>
<p class="title">360 Snapshots - Desktop, Mobile & VR</p>
<div class="panoMenu">
"""

footer = """</div>
</body>
</html>"""

print(f"Writing HTML to {MENU_HTML_FILENAME} ")
with open(MENU_HTML_FILENAME, 'w') as f:
    print(header, file=f)

    for source_file in source_filenames:
      
        print("working on: ", source_file)
        
        caption = source_file.replace('.jpg', '')
        caption = caption.replace('_', ' ')
        caption = caption.replace('-', ' ')
        caption = caption[(caption.rfind('/') + 1):].upper()

        item = f"""
            <div class="item">
                <a href="index.html?eqr={source_file}" target="_blank">
                    <img src="{source_file}" />
                    <span class="caption">{caption}</span>
                </a>
            </div>"""
        print(item, file=f)

    print(footer, file=f)
